import { Inter, Zilla_Slab } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const zilla = Zilla_Slab({
  subsets: ["latin"],
  variable: "--font-zilla",
  weight: ["400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${zilla.className}`}>{children}</body>
    </html>
  );
}
